### ISSUE TITLE
Use environmental variables for db config, falling back to defaults

### ISSUE THREAD

**Issue by OmenApps** [jacklinke/django-directed#1]
If a dev already has a local Postgres database or wants to use an external DBaaS rather than the provided docker-compose database, they should be able to override the test settings for database configuration with environmental variables.

**Comment by dalito** [comment]
This is already implemented (116583b7262fb241f68a8f0a7655b7246a32cd01).

BTW, are you still working on this package? It looks like a really nice start.

**Comment by jacklinke** [comment]
As noted by @dalito, this is already resolved.
